# Generated by Django 3.0.3 on 2020-02-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('invalid', 'Invalid')], default='new', max_length=10)),
                ('do_not_convert', models.BooleanField(default=False)),
                ('price_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=10)),
                ('price_amount', models.DecimalField(decimal_places=1, max_digits=10)),
                ('receive_currency', models.CharField(choices=[('BTC', 'BTC'), ('LTC', 'LTC'), ('ETH', 'ETH')], max_length=10)),
                ('receive_amount', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('payment_url', models.URLField()),
                ('created', models.DateTimeField()),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('underpaid_amount', models.IntegerField(default=0)),
                ('overpaid_amount', models.IntegerField(default=0)),
                ('is_refundable', models.BooleanField(default=False)),
            ],
        ),
    ]
