# Generated by Django 3.0.3 on 2020-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lightning_network',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receive_currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('LTC', 'LTC'), ('ETH', 'ETH')], default='BTC', max_length=10),
        ),
    ]
