# Generated by Django 3.0.3 on 2020-02-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingate', '0002_auto_20200207_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(max_length=50),
        ),
    ]
